// export const MAIN_ROUTE = '/'
// export const PRODUCT_ROUTE = '/product'
// export const PROFILE_ROUTE = '/profile'
// export const BASKET_ROUTE = '/basket'
// export const AUTH_ROUTE = '/auth'
// export const PIZZA_ROUTE = '/pizza'
// export const DRINKS_ROUTE = '/drinks'
// export const SAUCES_ROUTE = '/sauces'
// export const DESSERTS_ROUTE = '/desserts'


export const HOME = '/'
export const MENU = '/menu'
export const PROFILE = '/profile'
export const BASKET = '/basket'